name: CI workflow to check code Schema

on:
    workflow_dispatch: 

jobs:
    call-reusable-workflow-job:
        uses: ./.github/workflows/reusable-workflow.yaml

    notify-job:
        needs: call-reusable-workflow-job
        runs-on: ubuntu-latest
        steps:
            - name: notify
              run: |
                  echo "${{ needs.call-reusable-workflow-job.outputs.deployment_url }}
