name: 05 - JavaScript Action Demo

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name to greet'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install dependencies
        working-directory: ./.github/actions/workflow-summary
        run: npm install
      
      - name: Run JavaScript Action
        uses: ./.github/actions/workflow-summary
        with:
          name: ${{ github.event.inputs.name }}