name: Reusable workflow

on:
  workflow_call:
    outputs:
      deployment_url:
        value: $${{ jobs.deploy-job.outputs.deployment_url }}

jobs:
  deploy-job:
    runs-on: ubuntu-latest
    outputs:
      deployment_url: ${{ steps.deploy.outputs.deployment_url }}
    steps:
      - name: Deploy Application
        id: deploy
        run: |
          echo "deployment_url=https://manjot.com" >> $GITHUB_OUTPUT
